server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/api/courses/**
            - id: enrollment-service
              uri: lb://enrollment-service
              predicates:
                - Path=/api/enrollments/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: ${JWT_SECRET:EdnVAuth7xKp92LmQ4rTz61BvNc38WsYh}
